---
- name: Copy services folder to /opt
  copy:
    src: svc/
    dest: /opt/svc/
    mode: 0755

- name: Start docker composed services
  shell: "/opt/svc/start.sh"

- name: Get root SSH public key
  command: cat /root/id_rsa.pub
  register: ssh_key_out

- name: Add this public ssh key to your GitHub account
  debug:
    msg: "{{ssh_key_out.stdout}}"
