---
- name: Copy services folder to /opt
  copy:
    src: svc/
    dest: /opt/svc/
    mode: 0755

- name: Start docker composed services
  command:
    cmd: "/opt/svc/start.sh"
    chdir: "/opt/svc"
