---
- name: Copy fail2ban config file
  copy:
    src: files/jail.local
    dest: /etc/fail2ban/jail.local

- name: Restart fail2ban
  systemd:
    name: fail2ban
    enabled: true
    state: restarted